export const GET_DOCLIST_REQUEST = 'GET_DOCLIST_REQUEST';
export const GET_DOCLIST_SUCCESS = 'GET_DOCLIST_SUCCESS';
export const GET_DOCLIST_FAILURE = 'GET_DOCLIST_FAILURE';

export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_XML_DATA_SUCCESS = 'GET_XML_DATA_SUCCESS';
export const GET_XML_DATA_FAILURE = 'GET_XML_DATA_FAILURE';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

export const CREATE_NEW_DOCUMENT = 'CREATE_NEW_DOCUMENT';

export const CALCULATE_INITIAL_DATA = 'CALCULATE_INITIAL_DATA';

export const UPDATE_STORE = 'UPDATE_STORE';

export const SAVE_DATA_REQUEST = 'SAVE_DATA_REQUEST';
export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const SAVE_DATA_FAILURE = 'SAVE_DATA_FAILURE';
